### ISSUE TITLE
gke-volpod.yml

### ISSUE THREAD

**Issue by fuatu** [ACloudGuru-Resources/Kubernetes_Deep_Dive_NP#4]
This file has indentaation errors and it has also typos:
correct file details here:
```
apiVersion: v1
kind: Pod
metadata:
  name: volpod
spec:
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: pvc1
  containers:
  - name: ubuntu-ctr
    image: ubuntu:latest
    command:
    - /bin/bash
    - "-c"
    - "sleep 60m"
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /data
      name: data
```
